# This file overrides project settings from settings.yml for production.
# Copy this file, rename it to local_settings.yml and edit.
# It will not be checked into the version control system.

SECRET_KEY:

# A list of host/domain names that Django site can serve.
ALLOWED_HOSTS:
- localhost
- 127.0.0.1
- '[::1]'
- .example.com

DATABASES:
  default:
    ENGINE:   django.db.backends.postgresql_psycopg2
    NAME:     lerna
    USER:     ~
    PASSWORD: ~
    HOST:     localhost
    # PORT:   5432

# LOGGING:
#   version: 1
#   disable_existing_loggers: false
#   filters:
#   formatters:
#   handlers:
#   loggers:
#     django:

AUTH_PASSWORD_VALIDATORS:
- NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
  OPTIONS:
    user_attributes: [login, username, email]
- NAME: django.contrib.auth.password_validation.MinimumLengthValidator
  OPTIONS:
    min_length: 10
- NAME: django.contrib.auth.password_validation.CommonPasswordValidator
- NAME: django.contrib.auth.password_validation.NumericPasswordValidator
