# This file overrides project settings from settings.yml for development.
# Copy this file, rename it to local_settings.yml and edit.
# It will not be checked into the version control system.

DEBUG: true

SECRET_KEY: development_secret_key

INTERNAL_IPS: [127.0.0.1]

DATABASES:
  default:
    ENGINE:   django.db.backends.postgresql_psycopg2
    NAME:     lerna
    USER:     lerna_db_user
    PASSWORD: lerna_db_password
    HOST:     localhost
    # PORT:   5432

PREPEND:
  MIDDLEWARE_CLASSES:
  - debug_toolbar.middleware.DebugToolbarMiddleware

APPEND:
  INSTALLED_APPS:
  - debug_toolbar

OVERRIDE:
  PIPELINE:
    PIPELINE_ENABLED: false

# LOGGING:
#   version: 1
#   disable_existing_loggers: false
#   filters:
#   formatters:
#   handlers:
#   loggers:
#     django:

DEBUG_TOOLBAR_PATCH_SETTINGS: false

DEBUG_TOOLBAR_PANELS:
- debug_toolbar.panels.sql.SQLPanel
# - debug_toolbar.panels.versions.VersionsPanel
# - debug_toolbar.panels.timer.TimerPanel
- debug_toolbar.panels.request.RequestPanel
- debug_toolbar.panels.templates.TemplatesPanel
- debug_toolbar.panels.logging.LoggingPanel
- debug_toolbar.panels.staticfiles.StaticFilesPanel
- debug_toolbar.panels.settings.SettingsPanel
- debug_toolbar.panels.headers.HeadersPanel
- debug_toolbar.panels.cache.CachePanel
- debug_toolbar.panels.signals.SignalsPanel
- debug_toolbar.panels.redirects.RedirectsPanel
