###########################################################
# Local settings, must be overridden in local_settings.yml
###########################################################

SECRET_KEY:

ALLOWED_HOSTS:
- localhost
- 127.0.0.1
- '[::1]'
- .example.com

DATABASES:
  default:
    ENGINE:
    NAME:
    USER:
    PASSWORD:
    HOST:
    PORT:

LOGGING:
  version: 1
  disable_existing_loggers: false
  # filters:
  # formatters:
  # handlers:
  # loggers:
  #   django:

TESTER:
  PROBLEMS_DIRECTORY:
  CHECKERS_DIRECTORY:
  COMPILERS_DIRECTORY:
  RUNNERS_DIRECTORY:

###########################################################
# Global settings
###########################################################

DEBUG: false

# Application definition
INSTALLED_APPS:
- django.contrib.admin
- django.contrib.auth
- django.contrib.contenttypes
- django.contrib.sessions
- django.contrib.messages
- django.contrib.staticfiles
- ajax_select
- pipeline
- scripts
- core
- users
- news
- contests
- global_statistics
- dbtrash

MIDDLEWARE_CLASSES:
- django.contrib.sessions.middleware.SessionMiddleware
- django.middleware.common.CommonMiddleware
- django.middleware.csrf.CsrfViewMiddleware
- django.contrib.auth.middleware.AuthenticationMiddleware
- django.contrib.auth.middleware.SessionAuthenticationMiddleware
- django.contrib.messages.middleware.MessageMiddleware
- django.middleware.clickjacking.XFrameOptionsMiddleware
- django.middleware.security.SecurityMiddleware
- pipeline.middleware.MinifyHTMLMiddleware

ROOT_URLCONF: lerna.urls

TEMPLATES:
- BACKEND: django.template.backends.django.DjangoTemplates
  DIRS: [templates]
  APP_DIRS: true
  OPTIONS:
    context_processors:
    - django.template.context_processors.debug
    - django.template.context_processors.request
    - django.contrib.auth.context_processors.auth
    - django.contrib.messages.context_processors.messages

WSGI_APPLICATION: lerna.wsgi.application

# Internationalization
LANGUAGE_CODE: ru-RU

# TODO(viers): Do something with TZ, at least it must be moved to local settings
TIME_ZONE: Asia/Novosibirsk

USE_I18N: true

USE_L10N: true

USE_TZ: true

LOGGING_CONFIG: lerna.settings.init_logging

# Static files (CSS, JavaScript, Images)
# TODO(viers): Think about moving this in another file - this section could grow quite large
STATIC_ROOT: !path build/static

STATIC_URL: /static/

STATICFILES_STORAGE: pipeline.storage.PipelineCachedStorage

STATICFILES_FINDERS:
- django.contrib.staticfiles.finders.FileSystemFinder
- django.contrib.staticfiles.finders.AppDirectoriesFinder
- pipeline.finders.PipelineFinder

STATICFILES_DIRS:
- !path static/src

AJAX_SELECT_BOOTSTRAP: false

DEBUG_TOOLBAR_CONFIG:
  JQUERY_URL: /static/jquery/jquery.min.js

PIPELINE:
  PIPELINE_ENABLED: true

  JAVASCRIPT:
    jquery:
      source_filenames:
      - jquery/jquery.min.js
      - jquery/jquery-ui.min.js
      output_filename: jquery.piped.min.js
    foundation:
      source_filenames:
      - foundation/foundation.js
      - foundation/what-input.js
      output_filename: foundation.piped.min.js

  STYLESHEETS:
    jquery:
      source_filenames:
      - jquery-ui.min.css
      output_filename: jquery.piped.min.css
    foundation:
      source_filenames:
      - foundation/foundation.css
      output_filename: foundation.piped.min.css

  JS_COMPRESSOR: pipeline.compressors.NoopCompressor
  CSS_COMPRESSOR: pipeline.compressors.NoopCompressor

# Authorizing
AUTH_USER_MODEL: users.User
