########################################################
# Local settings, must be defined in local_settings.yml
########################################################

SECRET_KEY:

ALLOWED_HOSTS:
- localhost
- 127.0.0.1
- '[::1]'
- .example.com

DATABASES:
  default:
    ENGINE:
    NAME:
    USER:
    PASSWORD:
    HOST:
    PORT:

LOGGING:
  version: 1
  disable_existing_loggers: false

########################################################
# Global settings
########################################################

DEBUG: false

# Application definition
INSTALLED_APPS:
- django.contrib.admin
- django.contrib.auth
- django.contrib.contenttypes
- django.contrib.sessions
- django.contrib.messages
- django.contrib.staticfiles
- ajax_select
- messages_extends
- pipeline
# Project-local:
- scripts
- core
- users
- news
- achievements
- global_statistics
- dbtrash

MIDDLEWARE:
- django.contrib.sessions.middleware.SessionMiddleware
- django.middleware.common.CommonMiddleware
- django.middleware.csrf.CsrfViewMiddleware
- django.contrib.auth.middleware.AuthenticationMiddleware
- django.contrib.auth.middleware.SessionAuthenticationMiddleware
- django.contrib.messages.middleware.MessageMiddleware
- django.middleware.clickjacking.XFrameOptionsMiddleware
- django.middleware.security.SecurityMiddleware

ROOT_URLCONF: lerna.urls

TEMPLATES:
- BACKEND: django.template.backends.django.DjangoTemplates
  DIRS: [templates]
  APP_DIRS: true
  OPTIONS:
    context_processors:
    - django.template.context_processors.debug
    - django.template.context_processors.request
    - django.contrib.auth.context_processors.auth
    - django.contrib.messages.context_processors.messages

WSGI_APPLICATION: lerna.wsgi.application

EMAIL_SUBJECT_PREFIX: '[Lerna] '

# Internationalization
LANGUAGE_CODE: ru-RU
USE_I18N: true
USE_L10N: true
USE_TZ: true
FORMAT_MODULE_PATH: [lerna.formats]

# Source code highlighter
PYGMENTS:
  LEXER:
    tabsize: 4
  FORMATTER:
    style: tango
    linenos: table
  STYLE_SELECTORS: .highlight

# Universal document converter
PANDOC:
  REQUIRED: false
  EXTRA_ARGS: [--katex, --highlight-style=tango]
  FILTERS:
  - pandoc-anglequotes # https://github.com/SirNickolas/pandoc-anglequotes

LOGGING_CONFIG: lerna.settings.init_logging

# Authorizing
AUTH_USER_MODEL: users.User
LOGIN_URL: /login/

MESSAGE_STORAGE: messages_extends.storages.FallbackStorage
