###########################################################
# Local settings, must be overridden in local_settings.yml
###########################################################

SECRET_KEY:

ALLOWED_HOSTS:
- localhost
- 127.0.0.1
- '[::1]'
- .example.com

DATABASES:
  default:
    ENGINE:
    NAME:
    USER:
    PASSWORD:
    HOST:
    PORT:

LOGGING:
  version: 1
  disable_existing_loggers: false
  # filters:
  # formatters:
  # handlers:
  # loggers:
  #   django:

###########################################################
# Global settings
###########################################################

DEBUG: false

# Application definition
INSTALLED_APPS:
- django.contrib.admin
- django.contrib.auth
- django.contrib.contenttypes
- django.contrib.sessions
- django.contrib.messages
- django.contrib.staticfiles
- ajax_select
- pipeline
# Project-local.
- scripts
- core
- users
- news
- global_statistics
- dbtrash

MIDDLEWARE_CLASSES:
- django.contrib.sessions.middleware.SessionMiddleware
- django.middleware.common.CommonMiddleware
- django.middleware.csrf.CsrfViewMiddleware
- django.contrib.auth.middleware.AuthenticationMiddleware
- django.contrib.auth.middleware.SessionAuthenticationMiddleware
- django.contrib.messages.middleware.MessageMiddleware
- django.middleware.clickjacking.XFrameOptionsMiddleware
- django.middleware.security.SecurityMiddleware
# Disabled until it can work properly with 'contests:source' page.
# - pipeline.middleware.MinifyHTMLMiddleware

ROOT_URLCONF: lerna.urls

TEMPLATES:
- BACKEND: django.template.backends.django.DjangoTemplates
  DIRS: [templates]
  APP_DIRS: true
  OPTIONS:
    context_processors:
    - django.template.context_processors.debug
    - django.template.context_processors.request
    - django.contrib.auth.context_processors.auth
    - django.contrib.messages.context_processors.messages

WSGI_APPLICATION: lerna.wsgi.application

# Internationalization
LANGUAGE_CODE: ru-RU
# TODO(viers): Do something with TZ, at least it must be moved to local settings
TIME_ZONE: Asia/Novosibirsk
USE_I18N: true
USE_L10N: true
USE_TZ: true

LOGGING_CONFIG: lerna.settings.init_logging

# Authorizing
AUTH_USER_MODEL: users.User
LOGIN_URL: /login/
