STATIC_ROOT: !path build/static

STATIC_URL: /static/

STATICFILES_STORAGE: pipeline.storage.PipelineStorage

STATICFILES_FINDERS:
- django.contrib.staticfiles.finders.FileSystemFinder
- django.contrib.staticfiles.finders.AppDirectoriesFinder
- pipeline.finders.PipelineFinder

STATICFILES_DIRS:
- !path static/src

AJAX_SELECT_BOOTSTRAP: false

DEBUG_TOOLBAR_CONFIG:
  JQUERY_URL: /static/jquery/jquery.min.js

HTML_MINIFY: true

PIPELINE:
  PIPELINE_ENABLED: true

  COMPILERS:
  - lerna.static.sass.SassCompiler

  JAVASCRIPT:
    jquery:
      source_filenames:
      - jquery/jquery.min.js
      - jquery/jquery-ui.min.js
      output_filename: jquery.piped.min.js
    foundation:
      source_filenames:
      - foundation/foundation.js
      - foundation/foundation-launch.js
      - foundation/what-input.js
      output_filename: foundation.piped.min.js
    katex:
      source_filenames:
      - katex/katex.min.js
      - katex/katex-process.js
      output_filename: katex.piped.min.js

  STYLESHEETS:
    jquery:
      source_filenames:
      - jquery/jquery-ui.min.css
      output_filename: jquery.piped.min.css
    foundation:
      source_filenames:
      - foundation/foundation.css
      output_filename: foundation.piped.min.css
    katex:
      source_filenames:
      - katex/katex.min.css
      output_filename: katex.piped.min.css
    lerna:
      source_filenames:
      - lerna/overrides.scss
      - lerna/contests.scss
      - lerna/controls.scss
      - lerna/global.scss
      - lerna/news.scss
      - lerna/users.scss
      output_filename: lerna.piped.min.css

  JS_COMPRESSOR: pipeline.compressors.jsmin.JSMinCompressor
  CSS_COMPRESSOR: lerna.static.csscompressor.CSSCompressor

APPEND:
  MIDDLEWARE_CLASSES:
  - htmlmin.middleware.HtmlMinifyMiddleware
  - htmlmin.middleware.MarkRequestMiddleware
